name: CI

on:
  create:
    branches: 
      - release/**
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      DLL_NAME: 'OpenXmlPowerTools.NetCore'
      SOLUTION: './OpenXmlPowerTools.sln'
      MAIN_PROJECT: './OpenXmlPowerTools/OpenXmlPowerTools.csproj'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh
   
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
         6.0.x
         7.0.x
    - name: Build
      run: dotnet build $MAIN_PROJECT --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION

    - name: Run tests
      run: dotnet test $SOLUTION --no-restore --configuration $BUILD_CONFIG --verbosity minimal
      
    - name: Publish
      if: startsWith(github.ref, 'refs/heads/release')
      run: dotnet nuget push ./OpenXmlPowerTools/bin/$BUILD_CONFIG/$DLL_NAME.$BUILD_VERSION.nupkg -s 'https://api.nuget.org/v3/index.json' -k ${{secrets.NUGET_API_KEY}}
